version: "3.7"
services:
    app:
        build:
            args:
                user: momo
                uid: 1000
            context: ./dockerfiles
            dockerfile: Dockerfile
        image: appmail
        container_name: appmail-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - appmail

    db:
        container_name: appmail-db-pgsql
        image: postgres:14
        env_file: ./.env
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: /data/postgres14
        volumes:
            - appmail-db-pgsql14:/data/postgres14
        ports:
            - ${DB_PORT}:5432
        networks:
            - appmail
        restart: unless-stopped

#    admin:
#        image: adminer
#        restart: always
#        depends_on:
#            - db
#        ports:
#            - 8080:8080
#        networks:
#            - appmail

    nginx:
        image: nginx:alpine
        container_name: appmail-nginx
        restart: unless-stopped
        ports:
            - ${APPLICATION_PORT}:80
            #- 433:433
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - appmail

networks:
    appmail:
        driver: bridge

volumes:
    appmail-db-pgsql14:
